name: Backend CI Pipeline
on:
  push:
    branches:
      - "feature/*"

jobs: Test Pipeline
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello world!"
        run: echo "Hello world!"